Dead code cleanup
RoboCupULaval/StrategyIA pull request #523
Opened 2018-10-17 21:57 UTC by barch2712

2018-10-18 17:41 UTC, PhiBabin requested changes

2018-10-18 17:41 UTC, PhiBabin commented on ai/STA/Tactic/align_to_defense_wall.py
> +                    self.game_state.field.our_goal_area.upper_left - self.game_state.field.our_goal).norm
```
min_radius_over_penality_zone = ROBOT_RADIUS + \
 (self.game_state.field.our_goal_area.upper_left - self.game_state.field.our_goal).norm
```

2018-11-14 21:37 UTC, barch2712 commented on ai/STA/Tactic/align_to_defense_wall.py
> +                    self.game_state.field.our_goal_area.upper_left - self.game_state.field.our_goal).norm
done

2018-11-14 22:54 UTC, PhiBabin approved these changes

2018-11-28 21:21 UTC, merged