ajust zone for penalty kick
RoboCupULaval/StrategyIA pull request #539
Opened 2019-03-13 20:51 UTC by FlexyKV

la forbidden zone pour le penalty empechait le robot de kicker la balle. J'ai modifier la zone forbidden dans le cas d'un penalty. GOAALL

2019-03-13 20:52 UTC, wonwon0 commented
GO

2019-03-13 20:52 UTC, wonwon0 commented
JAI RÉVISER QU'IL Y AVAIT DU CODE DANS TA PR, GO FOR MERGE

2019-03-13 20:58 UTC, PhiBabin requested changes

2019-03-13 20:58 UTC, PhiBabin commented on ai/STA/Tactic/tactic_book.py
> +                   GoToPositionandback,
This tactic should not be added

2019-03-13 20:58 UTC, PhiBabin commented on ai/STA/Tactic/tactictest_go_and_back.py
> +
This tactic should not be added

2019-03-13 20:58 UTC, PhiBabin commented on dual_launch.sh
> +| python main.py config/sim.cfg yellow negative --start_in_auto  --engine_fps 30\
The fps should be 60 by default

2019-03-14 15:59 UTC, PhiBabin approved these changes

2019-03-14 16:00 UTC, merged